name: TranxCraft
main: com.wickedgaminguk.TranxCraft.TranxCraft
version: 2.0
authors: [HeXeRei452]
description: The custom developed plugin for TranxCraft.
website: http://www.tranxcraft.com/
commands:
    tranxcraft:
      usage: /<command>
      description: Displays useful information about TranxCraft.
      aliases: [tc]
    mong:
      usage: /<command> <player>
      description: Kick a player telling him to read the rules.
      aliases: [noob, GRTFR]
    donator:
      usage: /<command> <add|remove|activate>
      description: Donator Handling.
      aliases: [dn]
    admininfo:
      usage: /<command>
      description: How to apply for moderator on TranxCraft.
      aliases: [ai, modinfo, moderatorinfo, mi, admin, moderator]
    c:
      usage: /<command> <player>
      description: Changes your gamemode or someone elses to creative.
      aliases: [creative]
    a:
      usage: /<command> <player>
      description: Changes your gamemode or someone elses to adventure.
      aliases: [adventure]
    s:
      usage: /<command> <player>
      description: Changes your gamemode or someone elses to survival.
      aliases: [survival]