name: TranxCraft
main: com.wickedgaminguk.TranxCraft.TranxCraft
version: 4.3
authors: [HeXeRei452]
description: The custom developed plugin for TranxCraft.
website: http://www.tranxcraft.com/
commands:
    tranxcraft:
      usage: /<command>
      description: Displays useful information about TranxCraft.
      aliases: [tc]
    mong:
      usage: /<command> <player>
      description: Kicks a player telling the player to read the rules.
      aliases: [noob, GRTFR]
    donator:
      usage: /<command> <add|remove|activate>
      description: Donator Handling.
      aliases: [dn]
    admininfo:
      usage: /<command>
      description: How to apply for moderator on TranxCraft.
      aliases: [ai, modinfo, moderatorinfo, mi, admin, moderator]
    gtfo:
      usage: /<command> <player> <reason>
      description: Bans a player.
    fuckoff:
      usage: /<command> <player>
      description: Completely fucks over a player.
      aliases: [doom]
    cake:
      usage: /<command>
      description: Cake!
    melon:
      usage: /<command>
      description: Melons!
    grandslam:
      usage: /<command> <player> <reason>
      description: Slams a player to the ground.
      aliases: [gt, gs]
    catapult:
      usage: /<command> <player>
      description: Catapults a player.
    report:
      usage: /<command> <player> <reason>
      description: Reports a Player.
    ucpsync:
      usage: /<command>
      description: Syncs User Data.
    o:
      usage: /<command> <message>
      description: TranxCraft's Admin Chat
      aliases: [ac, adminchat]